"""
Retail Sales Analysis Dashboard
- Interactive Streamlit visualization app
- Reads from 5 analysis CSV files generated by retail_agent.py

Usage:
    streamlit run retail_dashboard.py
"""

import streamlit as st
import pandas as pd
import os
import plotly.graph_objects as go
import plotly.express as px


# Configure Streamlit page
st.set_page_config(
    page_title="Retail Analysis",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
    <style>
    .main { padding: 0rem 1rem; }
    h1 { color: #1f77b4; }
    </style>
""", unsafe_allow_html=True)


@st.cache_data
def load_analysis_data(output_dir='retail_analysis_output'):
    """Load all analysis CSV files"""
    data = {}
    
    files = {
        'category_month': '1_sales_by_category_month.csv',
        'category_gender': '2_sales_by_category_gender.csv',
        'top_categories': '3_top_categories.csv',
        'sales_month': '4_sales_by_month.csv',
        'category_gender_detail': '5_sales_category_gender.csv'
    }
    
    missing_files = []
    
    for key, filename in files.items():
        filepath = os.path.join(output_dir, filename)
        try:
            if os.path.exists(filepath):
                data[key] = pd.read_csv(filepath)
            else:
                missing_files.append(filename)
        except Exception as e:
            st.error(f"Error loading {filename}: {e}")
    
    return data, missing_files


def display_sales_by_month(data):
    """Tab 1: Sales Trends by Month"""
    if 'sales_month' not in data:
        st.warning("Sales by month data not available")
        return
    
    df = data['sales_month']
    
    col1, col2 = st.columns([3, 1])
    with col1:
        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=df['Month'],
            y=df['Total Sales Amount'],
            mode='lines+markers',
            name='Total Sales',
            line=dict(color='#1f77b4', width=3),
            marker=dict(size=10, color='#1f77b4'),
            fill='tozeroy',
            fillcolor='rgba(31, 119, 180, 0.2)'
        ))
        fig.update_layout(
            title="Total Sales Trend Over Time",
            xaxis_title="Month",
            yaxis_title="Total Sales Amount ($)",
            hovermode='x unified',
            template='plotly_white',
            height=500,
            showlegend=False
        )
        st.plotly_chart(fig, use_container_width=True)
    
    with col2:
        st.metric("Total Sales", f"${df['Total Sales Amount'].sum():,.0f}")
        st.metric("Average Monthly", f"${df['Total Sales Amount'].mean():,.0f}")
        st.metric("Peak Month", f"${df['Total Sales Amount'].max():,.0f}")
    
    with st.expander("View Data"):
        st.dataframe(df, use_container_width=True)


def display_top_categories(data):
    """Tab 2: Top Product Categories"""
    if 'top_categories' not in data:
        st.warning("Top categories data not available")
        return
    
    df = data['top_categories']
    
    # Allow user to select number of categories
    top_n = st.slider("Number of top categories to display", 5, min(20, len(df)), 10)
    df_top = df.head(top_n)
    
    fig = px.bar(
        df_top,
        x='Product Category',
        y='Total Sales Amount',
        title=f"Top {top_n} Product Categories by Sales",
        color='Total Sales Amount',
        color_continuous_scale='Viridis',
        height=500,
        text='Total Sales Amount'
    )
    fig.update_traces(texttemplate='$%{text:,.0f}', textposition='outside')
    fig.update_layout(
        xaxis_tickangle=-45,
        hovermode='x unified',
        showlegend=False
    )
    st.plotly_chart(fig, use_container_width=True)
    
    with st.expander("View All Categories"):
        st.dataframe(df, use_container_width=True)


def display_category_by_gender(data):
    """Tab 3: Category Sales by Gender"""
    if 'category_gender' not in data:
        st.warning("Category by gender data not available")
        return
    
    df = data['category_gender']
    
    # Choose visualization type
    viz_type = st.radio("Visualization Type", ["Grouped", "Stacked"], horizontal=True)
    
    barmode = 'group' if viz_type == "Grouped" else 'stack'
    
    fig = px.bar(
        df,
        x='Product Category',
        y='Total Amount',
        color='Gender',
        title="Total Sales by Category and Gender",
        barmode=barmode,
        height=500,
        color_discrete_sequence=['#FF6B6B', '#4ECDC4']
    )
    fig.update_layout(
        xaxis_tickangle=-45,
        hovermode='x unified',
        yaxis_title="Total Sales Amount ($)",
        xaxis_title="Product Category"
    )
    st.plotly_chart(fig, use_container_width=True)
    
    with st.expander("View Data"):
        st.dataframe(df, use_container_width=True)


def display_category_by_month(data):
    """Tab 4: Sales Trends by Category Over Time"""
    if 'category_month' not in data:
        st.warning("Category by month data not available")
        return
    
    df = data['category_month']
    
    categories = sorted(df['Product Category'].unique())
    selected_categories = st.multiselect(
        "Select Categories to Display",
        categories,
        default=categories[:5] if len(categories) > 5 else categories
    )
    
    if not selected_categories:
        st.warning("Please select at least one category")
        return
    
    filtered_df = df[df['Product Category'].isin(selected_categories)]
    
    fig = px.line(
        filtered_df,
        x='Month',
        y='Total Amount',
        color='Product Category',
        title="Sales Trends by Category Over Time",
        markers=True,
        height=500,
        line_shape='linear'
    )
    fig.update_layout(
        hovermode='x unified',
        yaxis_title="Total Sales Amount ($)",
        xaxis_title="Month"
    )
    st.plotly_chart(fig, use_container_width=True)
    
    with st.expander("View Data"):
        st.dataframe(filtered_df, use_container_width=True)


def display_detailed_breakdown(data):
    """Tab 5: Detailed Analysis by Category and Gender"""
    if 'category_gender_detail' not in data:
        st.warning("Detailed breakdown data not available")
        return
    
    df = data['category_gender_detail']
    
    # Row 1: Sales breakdown
    col1, col2 = st.columns(2)
    
    with col1:
        fig1 = px.bar(
            df,
            x='Category',
            y='Total Sales Amount',
            color='Gender',
            title="Total Sales by Category & Gender",
            barmode='stack',
            height=400,
            color_discrete_sequence=['#FF6B6B', '#4ECDC4']
        )
        fig1.update_layout(xaxis_tickangle=-45)
        st.plotly_chart(fig1, use_container_width=True)
    
    with col2:
        fig2 = px.bar(
            df,
            x='Gender',
            y='Transaction Count',
            color='Category',
            title="Transaction Count by Gender & Category",
            height=400
        )
        st.plotly_chart(fig2, use_container_width=True)
    
    # Row 2: Average sales and scatter
    col3, col4 = st.columns(2)
    
    with col3:
        fig3 = px.scatter(
            df,
            x='Transaction Count',
            y='Average Sales',
            size='Total Sales Amount',
            color='Gender',
            hover_data=['Category'],
            title="Transaction Count vs Average Sales",
            height=400,
            color_discrete_sequence=['#FF6B6B', '#4ECDC4']
        )
        fig3.update_layout(hovermode='closest')
        st.plotly_chart(fig3, use_container_width=True)
    
    with col4:
        st.markdown("### Data Summary")
        st.dataframe(df, use_container_width=True, height=400)


def main():
    """Main application"""
    st.title("Retail Sales Analysis Dashboard")
    
    # Load data
    data, missing_files = load_analysis_data()
    
    if missing_files:
        st.error(f"""
        ❌ Missing analysis files! Please run the agent first:
        
        ```bash
        python generateRetailAnalysis.py retail_sales.csv
        ```
        
        Missing files: {', '.join(missing_files)}
        """)
        return
    
    if not data:
        st.error("No analysis files found in 'retail_analysis_output' directory")
        return
    
    # Create tabs
    tabs = st.tabs([
        "Sales by Month",
        "Top Categories",
        "Category by Gender",
        "Category by Month",
        "Detailed Breakdown"
    ])
    
##Collaboration window##
    ##with st.sidebar:
        ##st.subheader("**Chat with Gen AI Agent**")
        ##messages = st.container(height=500)
        ##if prompt := st.chat_input("Enter your messages here"):
          ##  messages.chat_message("user").write(prompt)
          ##  messages.chat_message("supplier").write(f"Hi, there! Ok, let me take a look at that.")
    
    st.text("")
    st.divider()
    st.text("")


    # Populate tabs
    with tabs[0]:
        display_sales_by_month(data)
    
    with tabs[1]:
        display_top_categories(data)
    
    with tabs[2]:
        display_category_by_gender(data)
    
    with tabs[3]:
        display_category_by_month(data)
    
    with tabs[4]:
        display_detailed_breakdown(data)
    
    # Footer
    st.divider()
    col1, col2, col3 = st.columns(3)
    with col1:
        st.caption("Data Source: retail_analysis_output/")
    with col2:
        st.caption("Refresh: Press R")
    with col3:
        st.caption("Built with Streamlit & Plotly")


if __name__ == "__main__":
    main()